services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    environment:
      OLLAMA_ALLOW_NETWORK: "true"
      OLLAMA_HTTP_PORT: "11434"
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g
        reservations:
          cpus: '0.5'
          memory: 512m
    volumes:
      - ollama-data:/var/lib/ollama

volumes:
  ollama-data:
